services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.api
    ports:
      - 8080:80
    depends_on:
      - redis
    volumes:
      - ./app:/app
    networks:
      - public-network
      - private-network
    

  worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.worker
    deploy:
      replicas: 2
    depends_on:
      - redis
    volumes:
      - ./app:/app
    networks:
      - private-network
    
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - private-network

volumes:
  redis-data:

networks:
  private-network:
  public-network:


