FROM python:3.13-alpine

WORKDIR /app

COPY ./pyproject.toml /app/pyproject.toml

RUN pip install --no-cache-dir --upgrade .[worker]

COPY ./app /app/

ENV PYTHONPATH=/app

CMD ["arq", "worker.settings.WorkerSettings"]
