FROM python:3.13-alpine

WORKDIR /app

COPY ./pyproject.toml /app/pyproject.toml

RUN pip install --no-cache-dir --upgrade .[api]

COPY ./app /app

ENV PYTHONPATH=/app

CMD ["fastapi", "run", "main.py", "--port", "80", "--reload"]